In [1]:
#Листинг 2.3.азличные способы представления тензоров
import tensorflow as tf

import numpy as np

m1 = [[1.0, 2.0],[3.0, 4.0]]

m2 = np.array([[1.0, 2.0],[3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],[3.0, 4.0]])
print(type(m1))
print(type(m2))
print(type(m3))

t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
tЗ = tf.convert_to_tensor(m3, dtype=tf.float32)

print(type(t1))
print(type(t2))
print(type(tЗ))

t4 = tf.ones([500,500])*0.5
print(t4)



2022-12-12 11:03:05.910377: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 ...
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]], shape=(500, 500), dtype=float32)


2022-12-12 11:03:33.703450: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-12 11:03:33.736549: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [2]:
x = tf.constant([[1, 2]]) #-- Задаетпроизвопьныйтензор
negMatrix = tf.negative(x) #-- Меняетзнакэпементовтензора
print(negMatrix) #-- Выводит обьект


tf.Tensor([[-1 -2]], shape=(1, 2), dtype=int32)


In [3]:
x1 = tf.constant([[2,3], [4,5]])
x2 = tf.constant([[2,2], [3, 1]])
y = tf.pow(x1, x2)
print(y)


tf.Tensor(
[[ 4  9]
 [64  5]], shape=(2, 2), dtype=int32)


In [14]:
from math import pi
mean = 0.0
sigma = 1.0
x = tf.constant([[1, 2]], dtype=tf.float32)
tf.exp(tf.negative(tf.pow(x - mean, 2.0) / (2.0 * tf.pow(sigma, 2.0))), 1.0 / (sigma * tf.sqrt(2.0 * pi) ))

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.60653067, 0.13533528]], dtype=float32)>

In [17]:
import tensorflow as tf
with tf.compat.v1.Session() as sess:
    hello = tf.constant('hello world')
    print(sess.run(hello))

b'hello world'
